# Generated by Django 5.1.5 on 2025-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POOrderLines',
            fields=[
                ('po_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_line_num', models.DecimalField(decimal_places=1, max_digits=10)),
                ('po_header_id', models.IntegerField()),
                ('po_number', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_ordered', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.IntegerField(default=0)),
                ('quantity_accepted', models.IntegerField(default=0)),
                ('quantity_rejected', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"pos_dev"."po_order_lines"',
            },
        ),
    ]
