# Generated by Django 5.1.5 on 2025-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_inward', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poorderlines',
            table='pos_dev.Po_Order_Lines',
        ),
    ]
