# Generated by Django 5.1.5 on 2025-02-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_inward', '0002_alter_poorderlines_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorderlines',
            name='priority',
            field=models.CharField(default='nan', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poorderlines',
            name='quantity_invoice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poorderlines',
            name='uom',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poorderlines',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='poorderlines',
            table='"pos_dev"."po_order_lines"',
        ),
    ]
