# Generated by Django 5.1.5 on 2025-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='SET search_path TO pos_dev,public;',
            reverse_sql='SET search_path TO public;'
        ),
        migrations.CreateModel(
            name='GST',
            fields=[
                ('category_id', models.CharField(db_column='Category_ID', max_length=50, primary_key=True, serialize=False)),
                ('cgst', models.DecimalField(db_column='CGST', decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(db_column='SGST', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pos_dev.gst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceMaster',
            fields=[
                ('product', models.OneToOneField(
                    on_delete=models.CASCADE,
                    primary_key=True,
                    db_column='product_id',
                    to='pricing.Product'
                )),
                ('unit_cost', models.DecimalField(db_column='Unit_Cost', decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(db_column='Unit_Price', decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(db_column='Discount_Price', decimal_places=2, max_digits=10)),
                ('added_by', models.CharField(db_column='Added_By', max_length=50)),
                ('modified_by', models.CharField(db_column='Modified_By', max_length=50)),
                ('updated_on', models.DateTimeField(db_column='Updated_On')),
            ],
            options={
                'db_table': 'price_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PricingHistory',
            fields=[
                ('history_id', models.CharField(db_column='History_ID', max_length=100, primary_key=True, serialize=False)),
                ('unit_cost', models.DecimalField(db_column='Unit_Cost', decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(db_column='Unit_Price', decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(db_column='Discount_Price', decimal_places=2, max_digits=10)),
                ('discount_price_old', models.DecimalField(db_column='Discount_Price_Old', decimal_places=2, max_digits=10)),
                ('updated_on', models.DateTimeField(db_column='Updated_On')),
                ('added_by', models.CharField(db_column='Added_By', max_length=50)),
                ('modified_by', models.CharField(db_column='Modified_By', max_length=50)),
            ],
            options={
                'db_table': 'pos_dev.pricing_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='Product_ID', max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product_Name', max_length=255)),
                ('category_id', models.CharField(db_column='Category_ID', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='Created_Date')),
                ('added_by', models.CharField(db_column='Added_By', max_length=50)),
            ],
            options={
                'db_table': 'pos_dev.product',
                'managed': False,
            },
        ),
    ]
