# Generated by Django 5.1.5 on 2025-03-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gst',
            table='gst',
        ),
        migrations.AlterModelTable(
            name='pricinghistory',
            table='pricing_history',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
